# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.16                 # https://pyreadiness.org/3.9
  - pip=22.1.2                    # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==23.5.2        # https://rpaframework.org/releasenotes.html
    - robocorp-tasks==2.1.1      # https://pypi.org/project/robocorp-tasks/#history
    - robocorp-vault==1.0.0      # https://pypi.org/project/robocorp-vault/#history
    - robocorp-workitems==1.2.1  # https://pypi.org/project/robocorp-workitems/#history
    - openai==0.27.8             # https://pypi.org/project/openai/#history
    - sendgrid==6.10.0           # https://pypi.org/project/sendgrid/#history
